<#
.SYNOPSIS
    Generates a detection script using the Detection Strategy Hierarchy.
.DESCRIPTION
    Creates an Intune detection script following the order of precedence:
    MSI ProductCode -> Registry DisplayName/DisplayVersion -> File Version -> Winget List.
#>
function New-StandaloneDetectShim {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$PackageId,

        [Parameter()]
        [string]$DisplayName = '',

        [Parameter()]
        [string]$ProductCode = '',

        [Parameter()]
        [string]$MinVersion = '',

        [Parameter()]
        [string]$DetectionStrategy = 'RegistryDisplayVersion'
    )

    $scriptTemplate = @'
<#
.SYNOPSIS
    Intune Win32 Detection Script for __PACKAGE_ID__
    Generated by WingetIntune (Detection Strategy: __STRATEGY__)
#>
$packageId = '__PACKAGE_ID__'
$displayName = '__DISPLAY_NAME__'
$productCode = '__PRODUCT_CODE__'
$minVersion = '__MIN_VERSION__'

$installed = $false
$detectedVersion = $null

# 1. Primary Strategy: MSI ProductCode GUID Check
if ($productCode) {
    $msiPaths = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$productCode",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\$productCode"
    )
    foreach ($mp in $msiPaths) {
        if (Test-Path $mp) {
            $installed = $true
            $detectedVersion = (Get-ItemProperty -Path $mp -Name DisplayVersion -ErrorAction SilentlyContinue).DisplayVersion
            break
        }
    }
}

# 2. Secondary Strategy: 64-bit & 32-bit Registry View Scan
if (-not $installed) {
    $regPaths = @(
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
        'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',
        'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*'
    )

    foreach ($path in $regPaths) {
        try {
            $keys = Get-ItemProperty -Path $path -ErrorAction SilentlyContinue
            foreach ($key in $keys) {
                $match = $false
                if ($displayName -and $key.DisplayName -match [regex]::Escape($displayName)) {
                    $match = $true
                } elseif ($key.DisplayName -match [regex]::Escape($packageId)) {
                    $match = $true
                }

                if ($match) {
                    $installed = $true
                    $detectedVersion = $key.DisplayVersion
                    break
                }
            }
        } catch { }

        if ($installed) { break }
    }
}

# 3. Tertiary Strategy: Winget List Check
if (-not $installed) {
    try {
        $wingetPath = (Get-Command 'winget.exe' -ErrorAction SilentlyContinue).Source
        if ($wingetPath) {
            $output = & $wingetPath list --exact --id $packageId --source winget --accept-source-agreements 2>$null
            if ($output -match [regex]::Escape($packageId)) {
                $installed = $true
            }
        }
    } catch { }
}

# 4. Version Floor Evaluation
if ($installed) {
    if ($minVersion -and $detectedVersion) {
        try {
            if ([version]$detectedVersion -lt [version]$minVersion) {
                Write-Output "Non-Compliant: Installed version $detectedVersion is below required $minVersion."
                exit 1
            }
        } catch { }
    }

    Write-Output "Compliant: $packageId is installed (Version: $detectedVersion)."
    exit 0
} else {
    exit 1
}
'@

    $content = $scriptTemplate.Replace('__PACKAGE_ID__', $PackageId).Replace('__DISPLAY_NAME__', $DisplayName).Replace('__PRODUCT_CODE__', $ProductCode).Replace('__MIN_VERSION__', $MinVersion).Replace('__STRATEGY__', $DetectionStrategy)
    return $content
}
