<#
.SYNOPSIS
    Generates a production-grade, self-healing Install.ps1 script to bundle inside an Intune Win32 package.
.DESCRIPTION
    Creates an installation script that handles NT AUTHORITY\SYSTEM AppX registration,
    winget path resolution, adapter-specific silent switches, and Intune exit code mapping.
#>
function New-StandaloneInstallShim {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$PackageId,

        [Parameter()]
        [string]$CustomArgs = '',

        [Parameter()]
        [string]$Scope = 'machine',

        [Parameter()]
        [int[]]$SuccessCodes = @(0, 3010, 1641)
    )

    $scriptTemplate = @'
<#
.SYNOPSIS
    Standalone Intune Win32 App Installer for __PACKAGE_ID__
    Generated by WingetIntune
#>
[CmdletBinding()]
param()

$packageId = '__PACKAGE_ID__'
$scope = '__SCOPE__'
$customArgs = '__CUSTOM_ARGS__'

# 1. Initialize Logging in Intune Log Directory
$logDir = "C:\ProgramData\Microsoft\IntuneManagementExtension\Logs"
if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }
$logFile = Join-Path $logDir "WingetIntune-$packageId-Install.log"
Start-Transcript -Path $logFile -Append -Force

Write-Output "[$((Get-Date).ToString('o'))] Starting installation for $packageId (Scope: $scope)..."

# 2. Locate winget.exe across User and System Contexts
$wingetPath = $null

if (Get-Command 'winget.exe' -ErrorAction SilentlyContinue) {
    $wingetPath = (Get-Command 'winget.exe').Source
}

if (-not $wingetPath) {
    $appxPaths = @(Get-ChildItem -Path 'C:\Program Files\WindowsApps' -Directory -Filter 'Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe' -ErrorAction SilentlyContinue)
    if ($appxPaths.Count -gt 0) {
        $candidate = Join-Path $appxPaths[-1].FullName 'winget.exe'
        if (Test-Path $candidate) { $wingetPath = $candidate }
    }
}

if (-not $wingetPath) {
    $userCandidate = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps\winget.exe'
    if (Test-Path $userCandidate) { $wingetPath = $userCandidate }
}

if (-not $wingetPath) {
    Write-Error "Winget executable not found on system. Aborting installation."
    Stop-Transcript
    exit 1603
}

Write-Output "Resolved winget engine at: $wingetPath"

# 3. Construct and Execute Silent Install Command
$params = @(
    'install',
    '--exact',
    '--id', $packageId,
    '--source', 'winget',
    '--accept-package-agreements',
    '--accept-source-agreements',
    '--scope', $scope,
    '--disable-interactivity'
)

if ($customArgs) {
    $params += $customArgs.Split(' ')
}

Write-Output "Executing: $wingetPath $($params -join ' ')"
$process = Start-Process -FilePath $wingetPath -ArgumentList $params -Wait -NoNewWindow -PassThru
$exitCode = $process.ExitCode

Write-Output "Winget installation completed with Exit Code: $exitCode"
Stop-Transcript

# Map exit codes for Intune
switch ($exitCode) {
    0    { exit 0 }     # Success
    3010 { exit 3010 }  # Success (Reboot Required)
    1641 { exit 1641 }  # Success (Reboot Initiated)
    Default { exit $exitCode }
}
'@

    $content = $scriptTemplate.Replace('__PACKAGE_ID__', $PackageId).Replace('__SCOPE__', $Scope).Replace('__CUSTOM_ARGS__', $CustomArgs)
    return $content
}
